Resources:
  # S3 Bucket para Analytics
  AnalyticsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bookstore-analytics-${self:provider.stage}-328458381283
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30

  # IAM Role para Glue
  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: BookstoreGlueServiceRole-${self:provider.stage}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub "${AnalyticsBucket}/*"
                  - !Sub "${AnalyticsBucket}"

  # Glue Database
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: bookstore_analytics_${self:provider.stage}
        Description: Database for bookstore analytics

  # Glue Table para Purchases
  PurchasesGlueTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: purchases
        StorageDescriptor:
          Columns:
            - Name: purchase_id
              Type: string
            - Name: tenant_id
              Type: string
            - Name: user_id
              Type: string
            - Name: total_amount
              Type: double
            - Name: status
              Type: string
            - Name: payment_method
              Type: string
            - Name: created_at
              Type: timestamp
            - Name: items
              Type: array<struct<book_id:string,quantity:int,unit_price:double,subtotal:double>>
          Location: !Sub "s3://${AnalyticsBucket}/purchases/"
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          SerdeInfo:
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
        PartitionKeys:
          - Name: year
            Type: string
          - Name: month
            Type: string
          - Name: day
            Type: string

Outputs:
  AnalyticsBucketName:
    Description: Name of the S3 bucket for analytics
    Value: !Ref AnalyticsBucket
    Export:
      Name: ${self:service}-${self:provider.stage}-analytics-bucket

  GlueDatabaseName:
    Description: Name of the Glue database
    Value: !Ref GlueDatabase
    Export:
      Name: ${self:service}-${self:provider.stage}-glue-database
