service: stream-processors

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    ELASTICSEARCH_HOST: ${file(../../config/${self:provider.stage}.yml):ELASTICSEARCH_HOST}
    ANALYTICS_BUCKET: bookstore-analytics-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/bookstore-*/stream/*"
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
      Resource:
        - "arn:aws:s3:::bookstore-analytics-${self:provider.stage}-*/*"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    strip: false

functions:
  booksStreamProcessor:
    handler: books_stream_processor.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [BooksTable, StreamArn]
          batchSize: 10
          startingPosition: LATEST
          maximumBatchingWindowInSeconds: 5

  purchasesStreamProcessor:
    handler: purchases_stream_processor.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [PurchasesTable, StreamArn]
          batchSize: 10
          startingPosition: LATEST
          maximumBatchingWindowInSeconds: 5

resources:
  - ${file(../../infrastructure/dynamodb.yml)}
